
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int QSTR = 13;
  public static final int QUOT = 11;
  public static final int SEMI = 2;
  public static final int STRING_LITERAL = 12;
  public static final int LBRAC = 8;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int COMMA = 10;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int TIMES = 5;
  public static final int LPAREN = 6;
  public static final int RBRAC = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "LBRAC",
  "RBRAC",
  "COMMA",
  "QUOT",
  "STRING_LITERAL",
  "QSTR"
  };
}

